SET IDENTITY_INSERT [dbo].[cities] ON 

INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (1, N'Ahmednagar', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (2, N'Akola', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (3, N'Amravati', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (4, N'Aurangabad', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (5, N'Beed', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (6, N'Bhandara', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (7, N'Buldhana', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (8, N'Chandrapur', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (9, N'Dhule', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (10, N'Gadchiroli', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (11, N'Gondia', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (12, N'Hingoli', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (13, N'Jalgaon', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (14, N'Jalna', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (15, N'Kolhapur', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (16, N'Latur', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (17, N'Mahabaleshwar', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (18, N'Mumbai', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (19, N'Mumbai City', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (20, N'Mumbai Suburban', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (21, N'Nagpur', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (22, N'Nanded', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (23, N'Nandurbar', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (24, N'Nashik', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (25, N'Osmanabad', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (26, N'Parbhani', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (27, N'Pune', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (28, N'Raigad', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (29, N'Ratnagiri', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (30, N'Sangli', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (31, N'Satara', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (32, N'Sholapur', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (33, N'Sindhudurg', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (34, N'Thane', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (35, N'Wardha', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (36, N'Washim', 21)
INSERT [dbo].[cities] ([Id], [Name], [sid]) VALUES (37, N'Yavatmal', 21)
SET IDENTITY_INSERT [dbo].[cities] OFF
SET IDENTITY_INSERT [dbo].[Legislative] ON 

INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (1, N'Achalpur')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (2, N'Adampur')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (3, N'Aheri')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (4, N'Ahmadpur')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (5, N'Ahmednagar City')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (6, N'Airoli')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (7, N'Akkalkot')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10002, N'Akkalkuwa')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10003, N'Akola East')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10004, N'Akola West')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10005, N'Akole')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10006, N'Akot')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10007, N'Alibag')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10008, N'Amalner')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10009, N'Ambala Cantt')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10010, N'Ambala City')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10011, N'Ambegaon')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10012, N'Ambernath')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10013, N'Amgaon')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10014, N'Amravati')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10015, N'Andheri East')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10016, N'Andheri West')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10017, N'Anushakti Nagar')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10018, N'Arjuni Morgaon')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10019, N'Armori')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10020, N'Arni')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10021, N'Ashti')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10022, N'Assandh')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10023, N'Ateli')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10024, N'Aurangabad Central')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10025, N'Aurangabad East')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10026, N'Aurangabad West')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10027, N'Ausa')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10028, N'Badhra')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10029, N'Badkhal')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10030, N'Badli')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10031, N'Badnapur')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10032, N'Badnera')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10033, N'Badshahpur')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10034, N'Baghmara')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10035, N'Baglan')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10036, N'Bagodar')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10037, N'Bahadurgarh')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10038, N'Baharagora')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10039, N'Balapur')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10040, N'Ballabgarh')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10041, N'Ballarpur')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10042, N'Baramati')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10043, N'Barhait')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10044, N'Barhi')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10045, N'Barkagaon')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10046, N'Barkatha')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10047, N'Baroda')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10048, N'Barshi')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10049, N'Barwala')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10050, N'Basmath')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10051, N'Bawal')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10052, N'Bawani Khera')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10053, N'Beed')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10054, N'Belapur')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10055, N'Beri')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10056, N'Bermo')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10057, N'Bhandara')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10058, N'Bhandup West')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10059, N'Bhawanathpur')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10060, N'Bhiwandi East')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10061, N'Bhiwandi Rural')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10062, N'Bhiwandi West')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10063, N'Bhiwani')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10064, N'Bhokar')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10065, N'Bhokardan')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10066, N'Bhor')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10067, N'Bhosari')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10068, N'Bhusawal')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10069, N'Bisharmpur')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10070, N'Bishnupur')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10071, N'Boisar')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10072, N'Bokaro')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10073, N'Borio')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10074, N'Borivali')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10075, N'Brahmapuri')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10076, N'Buldhana')
INSERT [dbo].[Legislative] ([ID], [Name]) VALUES (10077, N'Byculla')
SET IDENTITY_INSERT [dbo].[Legislative] OFF
SET IDENTITY_INSERT [dbo].[Parliament] ON 

INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (1, N'Ahmednagar')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (2, N'Akola')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (3, N'Ambala (SC)')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (4, N'Amravati')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (5, N'Aurangabad')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (6, N'Baramati')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (7, N'Beed')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10002, N'Bhandara-Gondiya')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10003, N'Bhiwandi')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10004, N'Bhiwani-Mahendragarh')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10005, N'Buldhana')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10006, N'Chandrapur')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10007, N'Chatra')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10008, N'Dhanbad')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10009, N'Dhule')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10010, N'Dindori')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10011, N'Dumka')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10012, N'Faridabad')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10013, N'Gadchiroli-Chimur')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10014, N'Giridih')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10015, N'Godda')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10016, N'Gurgaon')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10017, N'Hatkanangle')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10018, N'Hazaribagh')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10019, N'Hingoli')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10020, N'Hisar')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10021, N'Jalgaon')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10022, N'Jalna')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10023, N'Jamshedpur')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10024, N'Kalyan')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10025, N'Karnal')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10026, N'Khunti')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10027, N'Kodarma')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10028, N'Kolhapur')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10029, N'Kurukshetra')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10030, N'Latur')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10031, N'Lohardaga')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10032, N'Madha')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10033, N'Maval')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10034, N'Mumbai North')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10035, N'Mumbai North Central')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10036, N'Mumbai North East')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10037, N'Mumbai North West')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10038, N'Mumbai South')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10039, N'Mumbai South Central')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10040, N'Nagpur')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10041, N'Nanded')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10042, N'Nandurbar')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10043, N'Nashik')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10044, N'Osmanabad')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10045, N'Palamau')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10046, N'Palghar')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10047, N'Parbhani')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10048, N'Pune')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10049, N'Raigad')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10050, N'Rajmahal')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10051, N'Ramtek')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10052, N'Ranchi')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10053, N'Ratnagiri-Sindhudurg')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10054, N'Raver')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10055, N'Rohtak')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10056, N'Sangli')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10057, N'Satara')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10058, N'Shirdi')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10059, N'Shirur')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10060, N'Singhbhum')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10061, N'Sirsa (SC)')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10062, N'Solapur')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10063, N'Sonipat')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10064, N'Thane')
INSERT [dbo].[Parliament] ([ID], [Name]) VALUES (10065, N'Wardha')
SET IDENTITY_INSERT [dbo].[Parliament] OFF
SET IDENTITY_INSERT [dbo].[Responsibilities] ON 

INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (1, N'Software Developer', 0)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (3, N'Tech. Lead', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (4, N'Project Manager', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (5, N'QA 1', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (6, N'Web Designer', 0)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (8, N'Network Admin', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (10, N'Office Manager', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (11, N'Developer 1', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (12, N'Developer 2', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (13, N'Developer 3', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (14, N'Developer 4', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (15, N'Business Analyst', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (16, N'Designer 1', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (18, N'QA 2', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (19, N'Marketing', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (20, N'Designer 3', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (21, N'KPO - Data Verification Operator rtrtr', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (22, N'KPO - Accounting Associate', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (23, N'KPO - Business Analyst', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (24, N'KPO - Senior Analyst', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (25, N'KPO - Assistant Team Lead', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (26, N'KPO - Team Lead', 1)
INSERT [dbo].[Responsibilities] ([ID], [Name], [IsEnabled]) VALUES (28, N'Process Manager', 1)
SET IDENTITY_INSERT [dbo].[Responsibilities] OFF
INSERT [dbo].[states] ([id], [Name]) VALUES (1, N'Andaman & Nicobar [AN]')
INSERT [dbo].[states] ([id], [Name]) VALUES (2, N'Andhra Pradesh [AP]')
INSERT [dbo].[states] ([id], [Name]) VALUES (3, N'Arunachal Pradesh [AR]')
INSERT [dbo].[states] ([id], [Name]) VALUES (4, N'Assam [AS]')
INSERT [dbo].[states] ([id], [Name]) VALUES (5, N'Bihar [BH]')
INSERT [dbo].[states] ([id], [Name]) VALUES (6, N'Chandigarh [CH]')
INSERT [dbo].[states] ([id], [Name]) VALUES (7, N'Chhattisgarh [CG]')
INSERT [dbo].[states] ([id], [Name]) VALUES (8, N'Dadra & Nagar Haveli [DN]')
INSERT [dbo].[states] ([id], [Name]) VALUES (9, N'Daman & Diu [DD]')
INSERT [dbo].[states] ([id], [Name]) VALUES (10, N'Delhi [DL]')
INSERT [dbo].[states] ([id], [Name]) VALUES (11, N'Goa [GO]')
INSERT [dbo].[states] ([id], [Name]) VALUES (12, N'Gujarat [GU]')
INSERT [dbo].[states] ([id], [Name]) VALUES (13, N'Haryana [HR]')
INSERT [dbo].[states] ([id], [Name]) VALUES (14, N'Himachal Pradesh [HP]')
INSERT [dbo].[states] ([id], [Name]) VALUES (15, N'Jammu & Kashmir [JK]')
INSERT [dbo].[states] ([id], [Name]) VALUES (16, N'Jharkhand [JH]')
INSERT [dbo].[states] ([id], [Name]) VALUES (17, N'Karnataka [KR]')
INSERT [dbo].[states] ([id], [Name]) VALUES (18, N'Kerala [KL]')
INSERT [dbo].[states] ([id], [Name]) VALUES (19, N'Lakshadweep [LD]')
INSERT [dbo].[states] ([id], [Name]) VALUES (20, N'Madhya Pradesh [MP]')
INSERT [dbo].[states] ([id], [Name]) VALUES (21, N'Maharashtra [MH]')
INSERT [dbo].[states] ([id], [Name]) VALUES (22, N'Manipur [MN]')
INSERT [dbo].[states] ([id], [Name]) VALUES (23, N'Meghalaya [ML]')
INSERT [dbo].[states] ([id], [Name]) VALUES (24, N'Mizoram [MM]')
INSERT [dbo].[states] ([id], [Name]) VALUES (25, N'Nagaland [NL]')
INSERT [dbo].[states] ([id], [Name]) VALUES (26, N'Orissa [OR]')
INSERT [dbo].[states] ([id], [Name]) VALUES (27, N'Pondicherry [PC]')
INSERT [dbo].[states] ([id], [Name]) VALUES (28, N'Punjab [PJ]')
INSERT [dbo].[states] ([id], [Name]) VALUES (29, N'Rajasthan [RJ]')
INSERT [dbo].[states] ([id], [Name]) VALUES (30, N'Sikkim [SK]')
INSERT [dbo].[states] ([id], [Name]) VALUES (31, N'Tamil Nadu [TN]')
INSERT [dbo].[states] ([id], [Name]) VALUES (32, N'Tripura [TR]')
INSERT [dbo].[states] ([id], [Name]) VALUES (33, N'Uttar Pradesh [UP]')
INSERT [dbo].[states] ([id], [Name]) VALUES (34, N'Uttaranchal [UT]')
INSERT [dbo].[states] ([id], [Name]) VALUES (35, N'West Bengal [WB]')

SET IDENTITY_INSERT [dbo].[UserMaster] ON 

INSERT [dbo].[UserMaster] ([UserID], [FirstName], [MiddleName], [LastName], [Gender], [EmailID], [MobileNumber], [Address], [City], [State], [Country], [Pincode], [ClinicName], [Username], [Password], [CreatedBy], [CreatedOn], [UpdatedBy], [UpdatedOn], [IsActive]) VALUES (1, N'Admin', NULL, N'Admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'admin', N'P9dDmuzTb8ZNsfeQZrNVOA==', NULL, NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[UserMaster] OFF
SET ANSI_PADDING ON
GO